repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      # Run the linter
      - id: ruff-check
        args: [ --fix, --extend-select, 'I' ]
      # Run the formatter
      - id: ruff-format
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.14'
    hooks:
      - id: vulture