[project]
name = "fell-finder"
version = "0.1.0"
description = "A personal project which aims to help you find the hilliest possible routes in your local area (so long as you're UK based)."
authors = [
    {name = "Ross Piper", email = "rp-webservices@outlook.com"}
]
license = {text = "MIT License"}
readme = "README.md"
dependencies = [
    "bng-latlon>=1.1",
    "dash-leaflet>=1.0.15",
    "dash[celery,diskcache]>=2.18.2",
    "geopy>=2.4.1",
    "gpxpy>=1.6.2",
    "networkx>=3.4.2",
    "numpy<2.0",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "polars>=1.17.1",
    "pyarrow>=18.1.0",
    "pyrosm>=0.6.2",
    "pyspark>=3.5.3",
    "pyyaml>=6.0.2",
    "rasterio>=1.4.3",
    "rustworkx>=0.15.1",
    "thefuzz>=0.22.1",
    "tqdm>=4.67.1",
]
requires-python = ">=3.12,<3.13"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "W", "D1", "D41", "ANN001", "ANN2", "FIX", "ERA"]
ignore = ["D107", "D415"]

[tool.ruff.lint.per-file-ignores]
"./tests/*" = ["E501", "ANN201"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.setuptools.packages.find]
where = ["src"]
include = ["fell_finder"]

[dependency-groups]
dev = [
    "jupyterlab>=4.3.4",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-xdist>=3.6.1",
    "ruff>=0.8.4",
]
