[tool.black]
line-length = 79

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "W", "D1", "D41", "ANN001", "ANN2", "FIX", "ERA"]
ignore = ["D107", "D415"]

[tool.ruff.lint.per-file-ignores]
"./tests/*" = ["E501", "ANN201"]

[tool.ruff.lint.pydocstyle]
convention = "google"