"""Contains the functions required to interface with the API provided by
fell_finder"""

import json
from dataclasses import fields
from typing import Any

import requests

from fell_viewer.common.containers import Route, RouteConfig


def _gen_request_url(config: RouteConfig) -> str:
    base_url = "http://localhost:8000/route/request"

    query = []
    for field in fields(config):
        field_val = getattr(config, field.name)
        if not field_val:
            continue
        if isinstance(field_val, list):
            field_val = ",".join(field_val)
        query.append(f"{field.name}={field_val}")
    query = "&".join(query)

    url = f"{base_url}?{query}"

    return url


def _gen_status_url(job_id: str) -> str:
    base_url = "http://localhost:8000/route/status"

    return f"{base_url}?job_id={job_id}"


def _gen_retrieve_url(job_id: str) -> str:
    base_url = "http://localhost:8000/route/retrieve"

    return f"{base_url}?job_id={job_id}"


def request_new_route(
    config: RouteConfig,
) -> str:
    """Based on the user-provided configuration, generate routes which match
    their requirements and return them for use in the webapp.

    Args:
        config: The user-provided configuration for route creation

    Returns:
        A list of generated routes

    """

    url = _gen_request_url(config)

    response = requests.get(url, headers={"Content-Type": "application/json"})

    print(f"Response is {response}")

    # TODO: Set other codes to display toast popups when progress bar is
    #       reinstated
    if response.status_code != 202:
        return ""

    job_id = json.loads(response.content)["job_id"]
    return job_id


def get_job_status(job_id: str) -> dict[str, Any]:
    """Fetch the status of the specified job from the fell_finder API. Output
    will be a dict containing 'status' and 'detail' keys.

    Args:
        job_id: The unique ID for the job to be fetched

    Returns:
        The current status of the job

    """
    url = _gen_status_url(job_id)

    response = requests.get(url, headers={"Content-Type": "application/json"})

    output = json.loads(response.content)

    return output


def get_job_results(job_id: str) -> list[Route]:
    """Fetch the result of the specified job from the fell_finder API. Output
    will be a list of Route objects.

    Args:
        job_id: The unique ID for the completed job

    Returns:
        The routes generated by the job

    """
    url = _gen_retrieve_url(job_id)

    response = requests.get(url, headers={"Content-Type": "application/json"})

    raw_routes = json.loads(response.content)

    generated = []
    for route in raw_routes:
        generated.append(Route.from_api_response(route))

    return generated
