"""Utility functions which either help to extract data which is helpful for
plotting, or generate plots which are featured on more than one page"""

import dash_leaflet as dl

from fell_viewer.containers.routes import (
    Route,
)


def generate_polyline_from_route(route: Route) -> dl.Polyline:
    """For a generated route, generate a dash-leaflet polyline which can be
    displayed on a map

    Args:
        graph: The graph which was used to generate the provided route
        route: A route generated by a RouteMaker

    Returns:
        A mapbox plot of the provided route

    """

    polyline = dl.Polyline(
        positions=route.geometry.coords,
        id="route-plot-trace",
        interactive=True,
    )

    return polyline
