"""Functions relating to the loading of a .osm.pbf network graph into a tabular
format
"""

import contextlib
import logging
import os
import shutil
from pathlib import Path

from bng_latlon import WGS84toOSGB36
from pyspark.sql import DataFrame, SparkSession, Window
from pyspark.sql import functions as F
from pyspark.sql import types as T

from fell_loader.base import BaseSparkLoader
from fell_loader.schemas.landing import EDGES_SCHEMA, NODES_SCHEMA

logger = logging.getLogger(__name__)

# cSpell: ignore: OSGB, parquetizer, latlon


class OsmLoader(BaseSparkLoader):
    """Reads in the contents of the provided OSM extract. Generates three
    parquet datasets containing details of the graph nodes, ways and edges.
    """

    # MARK: Class Setup

    def __init__(self, spark: SparkSession) -> None:
        """Create an instance of the OSM loader, store down the directory which
        contains the data to be loaded.
        """
        super().__init__(spark)

        self.skip_load = False
        self.binary_loc = Path(os.environ["FF_PARQUETIZER_LOC"])

        self._set_parquet_locs()

    def _set_parquet_locs(self) -> None:
        """Store the location of the parquet files generated by osm-parquetizer
        as a class attribute for convenience.

        Raises:
            FileNotFoundError: If no .parquet files are detected, an exception
                will be raised.

        """
        osm_loc = self.data_dir / "extracts" / "osm"

        nodes_loc = osm_loc.glob("*.node.parquet")
        ways_loc = osm_loc.glob("*.way.parquet")

        try:
            self.nodes_loc = next(nodes_loc)
            self.ways_loc = next(ways_loc)
        except StopIteration:
            raise FileNotFoundError(
                f"Unable to find generated parquet files in {osm_loc}. Please "
                "ensure you have called unpack_osm_pbf, and check the job"
                "logs"
            )

    # MARK: File Unpacking

    def _unpack_osm_pbf(self) -> None:
        """Use the osm-parquetizer utility to unpack the provided osm.pbf file
        in the extracts/osm directory into parquet files. These can then be
        read in as dataframes for further processing.

        Raises:
            FileNotFoundError: If no osm.pbf file is found in the extracts/osm
                subfolder of the data directory, an exception will be raised
            ValueError: If multiple osm.pbf files are found in the
                extracts/osm subfolder of the data directory, an exception will
                be raised

        """
        osm_loc = self.data_dir / "extracts" / "osm"
        pbf_loc = list(osm_loc.glob("*.osm.pbf"))

        # Check for source data
        if not pbf_loc:
            raise FileNotFoundError(f"No osm.pbf file detected in {pbf_loc}")
        if len(pbf_loc) > 1:
            pbf_str = ", ".join(pbf.as_posix() for pbf in pbf_loc)
            raise ValueError(
                f"Multiple osm.pbf files detected in {pbf_loc}: {pbf_str}"
            )
        pbf_loc = pbf_loc[0]

        # Check if file has changed from previous run
        checkpoint_file = self.data_dir / "landing" / "latest_osm.txt"
        if not checkpoint_file.exists():
            logger.info(
                "No record of previous files detected, "
                "OSM data will be reloaded"
            )
            last_file = None
        else:
            last_file = checkpoint_file.read_text().strip()
            logger.info(f"Previous file to be loaded was {last_file}")

        if pbf_loc.as_posix() == last_file:
            logger.info("OSM data has not changed, and will not be reloaded")
            self.skip_load = True
            return
        logger.info(f"New file is {pbf_loc.as_posix()}")

        # Unpack source file
        logger.info(f"Unpacking {pbf_loc}")
        os.system(f"java -jar {self.binary_loc} {pbf_loc}")
        checkpoint_file.write_text(pbf_loc.as_posix())
        logger.info("File processed successfully")

    def read_osm_data(self) -> tuple[DataFrame, DataFrame] | tuple[None, None]:
        """Read in the contents of the OSM nodes/ways parquet files as
        spark dataframes. Note that this can only be called after
        unpack_osm_pbf.

        Returns:
            A dataframe containing the nodes, and a dataframe containing the
            ways

        """
        # Unpack OSM data to parquet
        self._unpack_osm_pbf()

        if self.skip_load:
            return None, None

        # Retain location of generated files
        self._set_parquet_locs()

        logger.debug("Reading generated parquet files")
        nodes_df = self.spark.read.parquet(self.nodes_loc.as_posix())
        ways_df = self.spark.read.parquet(self.ways_loc.as_posix())

        return nodes_df, ways_df

    # MARK: Node Parsing

    @staticmethod
    def assign_bng_coords(nodes: DataFrame) -> DataFrame:
        """Assign each node an easting and northing, this will be used to
        join the nodes/edges of the map onto the elevation data provided by
        DEFRA.

        Args:
            nodes: The nodes dataframe

        Returns:
            A copy of the input dataframe with additional easting and northing
            columns

        """

        @F.udf(
            returnType=T.StructType(
                [
                    T.StructField("easting", T.DoubleType()),
                    T.StructField("northing", T.DoubleType()),
                ]
            )
        )
        def bng_udf(lat: float, lon: float) -> dict[str, float]:
            easting, northing = WGS84toOSGB36(lat, lon)
            return dict(easting=easting, northing=northing)

        nodes = nodes.withColumn(
            "bng_coords", bng_udf(F.col("latitude"), F.col("longitude"))
        )

        nodes = nodes.withColumn(
            "easting",
            F.col("bng_coords.easting").astype(T.IntegerType()),
        )

        nodes = nodes.withColumn(
            "northing",
            F.col("bng_coords.northing").astype(T.IntegerType()),
        )

        nodes = nodes.drop("bng_coords")

        return nodes

    @staticmethod
    def rename_coord_fields(df: DataFrame) -> DataFrame:
        """Rename 'latitude' and 'longitude' to 'lat' and 'lon' for brevity

        Args:
            df: A dataframe containing 'latitude' and 'longitude' columns

        Returns:
            A modified view of the provided dataframe with renames applied

        """
        return df.withColumnsRenamed({"latitude": "lat", "longitude": "lon"})

    # MARK: Edge Parsing

    @staticmethod
    def unpack_tags(ways: DataFrame) -> DataFrame:
        """Transform the tags for each way from the input format:

            [{key=tag_1, value=value_1}, {key=tag_2, value=value_2}]

        into a more usable mapping:

            {tag_1: value_1, tag_2: value_2}


        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A view of the input dataframe, with a processed tags column

        """

        @F.udf(returnType=T.MapType(T.StringType(), T.StringType()))
        def tags_udf(tags: list[dict]) -> dict[str, str]:
            tags_dict = {}
            for tag in tags:
                key = tag["key"].decode("utf8")
                value = tag["value"].decode("utf8")
                tags_dict[key] = value

            return tags_dict

        ways = ways.withColumn("tags", tags_udf(F.col("tags")))

        return ways

    def get_roads_and_paths(self, ways: DataFrame) -> DataFrame:
        """A Way in the OSM dataset may represent areas on the map (e.g.
        woodland) as well as paths and roads. For the purposes of generating
        running routes, we're only interested in the latter. We can determine
        if a Way is part of the road/path network based on the presence of the
        'highway' tag. The highway tag is retained as a new column for use
        downstream.

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A filtered copy of the input dataset with a new 'highway' column

        """
        ways = ways.filter(F.col("tags").getItem("highway").isNotNull())

        return ways

    @staticmethod
    def generate_edges(ways: DataFrame) -> DataFrame:
        """A single way will be comprised of multiple edges. In order to
        generate a network graph, we must unpack each way into edges. E.g. a
        Way might cross nodes 0, 7, 25 and 42. This must be unpacked into the
        edges: 0-7, 7-25 and 25-42.

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            An exploded view of the provided dataset, with one row for
            every edge contained within a way

        """
        # Explode the ways out to a single node per record
        edges = ways.select(
            F.col("id").alias("way_id"),
            F.col("tags"),
            F.explode(F.col("nodes")).alias("node"),
            F.col("timestamp"),
        )

        # Extract the node ID and index (in the way) from the struct which
        # represents the node
        edges = edges.withColumn("way_inx", F.col("node").getItem("index"))
        edges = edges.withColumn("src", F.col("node").getItem("nodeId"))

        # For each node, generate an edge by determining the next (destination)
        # node in the way.
        window_spec = Window.partitionBy(F.col("way_id")).orderBy(
            F.col("way_inx")
        )
        edges = edges.withColumn("dst", F.lead(F.col("src")).over(window_spec))
        edges = edges.dropna(subset=["src", "dst"], how="any").drop("node")

        return edges

    @staticmethod
    def get_edge_start_coords(nodes: DataFrame, edges: DataFrame) -> DataFrame:
        """For each edge in the graph, work out its starting position by
        joining on details of the source node.

        Args:
            nodes: A dataframe containing details of all nodes in the graph
            edges: A dataframe containing details of all edges in the graph

        Returns:
            A copy of the edges dataframe with additional src_lat, src_lon,
            src_easting, src_northing columns

        """
        nodes = nodes.select(
            F.col("id").alias("src"),
            F.col("lat").alias("src_lat"),
            F.col("lon").alias("src_lon"),
            F.col("easting").alias("src_easting"),
            F.col("northing").alias("src_northing"),
        )

        edges = edges.join(nodes, on="src", how="inner")

        return edges

    @staticmethod
    def get_edge_end_coords(nodes: DataFrame, edges: DataFrame) -> DataFrame:
        """For each edge in the graph, work out its final position by joining
        on details of the destination node.

        Args:
            nodes: A dataframe containing details of all nodes in the graph
            edges: A dataframe containing details of all edges in the graph

        Returns:
            A copy of the edges dataframe with additional dst_lat, dst_lon,
            dst_easting and dst_northing columns

        """
        nodes = nodes.select(
            F.col("id").alias("dst"),
            F.col("lat").alias("dst_lat"),
            F.col("lon").alias("dst_lon"),
            F.col("easting").alias("dst_easting"),
            F.col("northing").alias("dst_northing"),
        )

        edges = edges.join(nodes, on="dst", how="inner")

        return edges

    # MARK: Main Runner

    def clear_temp_files(self) -> None:
        """One the data load operation has finished, clear out any files in
        the temp directory
        """
        logger.info("Clearing temp directory")
        with contextlib.suppress(FileNotFoundError):
            shutil.rmtree((self.data_dir / "temp" / "nodes").as_posix())

    def run(self) -> None:
        """End-to-end data load script for an OSM extract. This will read in
        the contents of the file using pyrosm, perform some basic processing to
        ensure the resultant graph will be bidirectional and way geometry
        will be preserved when processed by pyspark. Nodes and edges will be
        assigned to partitions according to eastings & northings before being
        written out to disk.
        """
        nodes, ways = self.read_osm_data()
        if (nodes is None) or (ways is None):
            if not self.skip_load:
                raise ValueError("Unhandled exception while reading map data")
            return

        nodes = self.assign_bng_coords(nodes)
        nodes = self.rename_coord_fields(nodes)

        # Write out nodes, read in output to save re-evaluating transforms
        self.write_parquet(nodes, layer="temp", dataset="nodes")
        nodes = self.read_parquet(layer="temp", dataset="nodes")

        ways = self.unpack_tags(ways)
        ways = self.get_roads_and_paths(ways)

        self.write_parquet(ways, layer="landing", dataset="ways")
        ways = self.read_parquet(layer="landing", dataset="ways")

        edges = self.generate_edges(ways)
        edges = self.get_edge_start_coords(nodes, edges)
        edges = self.get_edge_end_coords(nodes, edges)

        edges = self.map_to_schema(edges, EDGES_SCHEMA)
        self.write_parquet(edges, layer="landing", dataset="edges")

        edges = self.read_parquet(layer="landing", dataset="edges")
        nodes = self.drop_unused_nodes(nodes, edges)
        nodes = self.map_to_schema(nodes, NODES_SCHEMA)
        self.write_parquet(nodes, layer="landing", dataset="nodes")
