"""Functions relating to the loading of a .osm.pbf network graph into a tabular
format"""

import os
from glob import glob
from typing import Literal

from bng_latlon import WGS84toOSGB36
from pyspark.sql import DataFrame, SparkSession, Window
from pyspark.sql import functions as F
from pyspark.sql import types as T


class OsmLoader:
    """Reads in the contents of the provided OSM extract. Generates three
    parquet datasets containing details of the graph nodes, ways and edges."""

    # MARK: Class Setup

    def __init__(self, spark: SparkSession) -> None:
        """Create an instance of the OSM loader, store down the directory which
        contains the data to be loaded."""

        self.spark = spark

        self.data_dir = os.environ["FF_DATA_DIR"]
        self.binary_loc = os.environ["FF_PARQUETIZER_LOC"]

        self.nodes_loc = ""
        self.ways_loc = ""

    def _set_parquet_locs(self) -> None:
        """Store the location of the parquet files generated by osm-parquetizer
        as a class attribute for convenience.

        Raises:
            FileNotFoundError: If no .parquet files are detected, an exception
                will be raised.

        """
        osm_loc = os.path.join(self.data_dir, "temp", "osm")

        nodes_loc = glob(os.path.join(osm_loc, "*.node.parquet"))
        ways_loc = glob(os.path.join(osm_loc, "*.way.parquet"))

        try:
            self.nodes_loc = nodes_loc[0]
            self.ways_loc = ways_loc[0]
        except IndexError:
            raise FileNotFoundError(
                f"Unable to find generated parquet files in {osm_loc}. Please "
                "ensure you have called unpack_osm_pbf, and check the job"
                "logs"
            )

    # MARK: File Unpacking

    def _unpack_osm_pbf(self) -> None:
        """Use the osm-parquetizer utility to unpack the provided osm.pbf file
        in the extracts/osm directory into parquet files. These can then be
        read in as dataframes for further processing.

        Raises:
            FileNotFoundError: If no osm.pbf file is found in the extracts/osm
                subfolder of the data directory, an exception will be raised
            RuntimeError: If multiple osm.pbf files are found in the
                extracts/osm subfolder of the data directory, an exception will
                be raised

        """

        pbf_loc = glob(
            os.path.join(self.data_dir, "extracts", "osm", "*.osm.pbf")
        )

        if not pbf_loc:
            raise FileNotFoundError(f"No osm.pbf file detected in {pbf_loc}")
        elif len(pbf_loc) > 1:
            pbf_str = ", ".join(pbf_loc)
            raise RuntimeError(
                f"Multiple osm.pbf files detected in {pbf_loc}: {pbf_str}"
            )
        else:
            pbf_loc = pbf_loc[0]

        os.system(f"java -jar {self.binary_loc} {pbf_loc}")

        self._set_parquet_locs()

    def read_osm_data(self) -> tuple[DataFrame, DataFrame]:
        """Read in the contents of the OSM nodes/ways parquet files as
        daft dataframes. Note that this can only be called after
        unpack_osm_pbf.

        Returns:
            A dataframe containing the nodes, and a dataframe containing the
            ways

        """

        try:
            self._set_parquet_locs()
        except FileNotFoundError:
            self._unpack_osm_pbf()
            self._set_parquet_locs()

        nodes_df = self.spark.read.parquet(self.nodes_loc)
        ways_df = self.spark.read.parquet(self.ways_loc)

        return nodes_df, ways_df

    # MARK: Node Parsing

    @staticmethod
    def assign_bng_coords(nodes: DataFrame) -> DataFrame:
        """Assign each node an easting and northing, this will be used to
        join the nodes/edges of the map onto the elevation data provided by
        DEFRA.

        Args:
            nodes: The nodes dataframe

        Returns:
            A copy of the input dataframe with additional easting and northing
            columns

        """

        @F.udf(
            returnType=T.StructType(
                [
                    T.StructField("easting", T.DoubleType()),
                    T.StructField("northing", T.DoubleType()),
                ]
            )
        )
        def bng_udf(lat: float, lon: float) -> dict[str, float]:
            easting, northing = WGS84toOSGB36(lat, lon)
            return dict(easting=easting, northing=northing)

        nodes = nodes.withColumn(
            "bng_coords", bng_udf(F.col("latitude"), F.col("longitude"))
        )

        nodes = nodes.withColumn(
            "easting",
            F.col("bng_coords.easting").astype(T.IntegerType()),
        )

        nodes = nodes.withColumn(
            "northing",
            F.col("bng_coords.northing").astype(T.IntegerType()),
        )

        nodes = nodes.drop("bng_coords")

        return nodes

    @staticmethod
    def set_node_output_schema(nodes: DataFrame) -> DataFrame:
        """Ensure the node output dataset contains only the required columns

        Args:
            nodes: A dataframe containing details of all nodes in the graph

        Returns:
            A subset of the provided dataframe

        """
        nodes = nodes.select(
            "id",
            F.col("latitude").alias("lat"),
            F.col("longitude").alias("lon"),
            "easting",
            "northing",
            "timestamp",
        )
        return nodes

    # MARK: Edge Parsing

    @staticmethod
    def unpack_tags(ways: DataFrame) -> DataFrame:
        """Transform the tags for each way from the input format:

            [{key=tag_1, value=value_1}, {key=tag_2, value=value_2}]

        into a more usable mapping:

            {tag_1: value_1, tag_2: value_2}


        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A view of the input dataframe, with a processed tags column

        """

        @F.udf(returnType=T.MapType(T.StringType(), T.StringType()))
        def tags_udf(tags: list[dict]) -> dict[str, str]:
            tags_dict = {}
            for tag in tags:
                key = tag["key"].decode("utf8")
                value = tag["value"].decode("utf8")
                tags_dict[key] = value

            return tags_dict

        ways = ways.withColumn("tags", tags_udf(F.col("tags")))

        return ways

    def get_roads_and_paths(self, ways: DataFrame) -> DataFrame:
        """A Way in the OSM dataset may represent areas on the map (e.g.
        woodland) as well as paths and roads. For the purposes of generating
        running routes, we're only interested in the latter. We can determine
        if a Way is part of the road/path network based on the presence of the
        'highway' tag. The highway tag is retained as a new column for use
        downstream.

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A filtered copy of the input dataset with a new 'highway' column

        """

        ways = ways.filter(F.col("tags").getItem("highway").isNotNull())

        return ways

    @staticmethod
    def generate_edges(ways: DataFrame) -> DataFrame:
        """A single way will be comprised of multiple edges. In order to
        generate a network graph, we must unpack each way into edges. E.g. a
        Way might cross nodes 0, 7, 25 and 42. This must be unpacked into the
        edges: 0-7, 7-25 and 25-42.

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            An exploded view of the provided dataset, with one row for
            every edge contained within a way

        """

        # Explode the ways out to a single node per record
        edges = ways.select(
            F.col("id").alias("way_id"),
            F.col("tags"),
            F.explode(F.col("nodes")).alias("node"),
            F.col("timestamp"),
        )

        # Extract the node ID and index (in the way) from the struct which
        # represents the node
        edges = edges.withColumn("way_inx", F.col("node").getItem("index"))
        edges = edges.withColumn("src", F.col("node").getItem("nodeId"))

        # For each node, generate an edge by determining the next (destination)
        # node in the way.
        window_spec = Window.partitionBy(F.col("way_id")).orderBy(
            F.col("way_inx")
        )
        edges = edges.withColumn("dst", F.lead(F.col("src")).over(window_spec))
        edges = edges.dropna(subset=["src", "dst"], how="any").drop("node")

        return edges

    @staticmethod
    def get_edge_start_coords(nodes: DataFrame, edges: DataFrame) -> DataFrame:
        """For each edge in the graph, work out its starting position by
        joining on details of the source node.

        Args:
            nodes: A dataframe containing details of all nodes in the graph
            edges: A dataframe containing details of all edges in the graph

        Returns:
            A copy of the edges dataframe with additional src_lat, src_lon,
            src_easting, src_northing columns

        """
        nodes = nodes.select(
            F.col("id").alias("src"),
            F.col("lat").alias("src_lat"),
            F.col("lon").alias("src_lon"),
            F.col("easting").alias("src_easting"),
            F.col("northing").alias("src_northing"),
        )

        edges = edges.join(nodes, on="src", how="inner")

        return edges

    @staticmethod
    def get_edge_end_coords(nodes: DataFrame, edges: DataFrame) -> DataFrame:
        """For each edge in the graph, work out its final position by joining
        on details of the destination node.

        Args:
            nodes: A dataframe containing details of all nodes in the graph
            edges: A dataframe containing details of all edges in the graph

        Returns:
            A copy of the edges dataframe with additional dst_lat, dst_lon,
            dst_easting and dst_northing columns

        """
        nodes = nodes.select(
            F.col("id").alias("dst"),
            F.col("lat").alias("dst_lat"),
            F.col("lon").alias("dst_lon"),
            F.col("easting").alias("dst_easting"),
            F.col("northing").alias("dst_northing"),
        )

        edges = edges.join(nodes, on="dst", how="inner")

        return edges

    @staticmethod
    def set_edge_output_schema(edges: DataFrame) -> DataFrame:
        """Ensure the edge output dataset contains only the required columns

        Args:
            edges: A dataframe containing details of all edges in the graph

        Returns:
            A subset of the provided dataframe

        """

        edges = edges.select(
            "src",
            "dst",
            "way_id",
            "way_inx",
            "src_lat",
            "src_lon",
            "dst_lat",
            "dst_lon",
            "src_easting",
            "src_northing",
            "dst_easting",
            "dst_northing",
            "tags",
            "timestamp",
        )
        return edges

    # MARK: Write Outputs

    def write_to_parquet(
        self, df: DataFrame, target: Literal["nodes", "ways", "edges"]
    ) -> None:
        """Write the contents of the provided dataframe out to the specified
        dataset location in the 'landing' layer of the data directory

        Args:
            df: The dataframe to be written
            target: The name of the dataset being written

        """
        tgt_loc = os.path.join(self.data_dir, "landing", target)

        df.write.parquet(tgt_loc, mode="overwrite")

    def read_from_parquet(
        self, target: Literal["nodes", "ways", "edges"]
    ) -> DataFrame:
        """Read the contents of the specified dataset into a dataframe

        Args:
            target: The name of the dataset to be read

        Returns:
            A dataframe representing the specified dataset

        """
        tgt_loc = os.path.join(self.data_dir, "landing", target)

        df = self.spark.read.parquet(tgt_loc)

        return df

    def load(self) -> None:
        """End-to-end data load script for an OSM extract. This will read in
        the contents of the file using pyrosm, perform some basic processing to
        ensure the resultant graph will be bidirectional and way geometry
        will be preserved when processed by pyspark. Nodes and edges will be
        assigned to partitions according to eastings & northings before being
        written out to disk.
        """

        nodes, ways = self.read_osm_data()

        nodes = self.assign_bng_coords(nodes)
        nodes = self.set_node_output_schema(nodes)

        self.write_to_parquet(nodes, "nodes")
        nodes = self.read_from_parquet("nodes")

        ways = self.unpack_tags(ways)
        ways = self.get_roads_and_paths(ways)

        self.write_to_parquet(ways, "ways")
        ways = self.read_from_parquet("ways")

        edges = self.generate_edges(ways)
        edges = self.get_edge_start_coords(nodes, edges)
        edges = self.get_edge_end_coords(nodes, edges)
        edges = self.set_edge_output_schema(edges)

        self.write_to_parquet(edges, "edges")
