[package]
name = "fell-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = { version = "0.7.1", features = ["serde-1"] }
geo = "0.29.3"
sqlx = { version = "0.8.3", features = ["macros", "postgres", "runtime-tokio"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
rayon = "1.10.0"
rustc-hash = "2.1.1"
indicatif = "0.17.11"
axum = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
opt-level = 3
