"""Primary execution script (for now). Triggers ingestion of LIDAR and OSM
data, joins the two datasets together to create a single augmented graph.
"""

# ruff: noqa: ERA001, E501, F401, RUF100

import logging
import os
import shutil
from datetime import datetime
from pathlib import Path

from delta import configure_spark_with_delta_pip
from fell_loader.landing import (
    LidarLoader,
    OsmLoader,
)
from fell_loader.optimising import GraphOptimiser
from fell_loader.sanitising import EdgeSanitiser, NodeSanitiser
from fell_loader.staging import EdgeStager, NodeStager
from fell_loader.uploading import GraphUploader
from pyspark.sql import SparkSession

if __name__ == "__main__":
    # Logging #################################################################
    # TODO: Define handler with filters to collect only fell_finder logs
    # TODO: Move this code into utils

    log_dir = (Path.cwd()) / "logs"
    if not log_dir.exists():
        log_dir.mkdir()

    now = datetime.now().isoformat(timespec="seconds")
    handler = logging.FileHandler(filename=f"logs/{now}.log")

    class FellFilter(logging.Filter):
        """Logging filter which returns only logs from fell_finder and its
        related packages
        """

        def filter(self, record: logging.LogRecord) -> bool:
            """Filter out records from upstream packages, retaining only those
            generated by fell_finder
            """
            return "fell_" in record.name or record.name == "__main__"

    fell_filter = FellFilter()

    fell_formatter = logging.Formatter(
        fmt="%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    )

    handler.addFilter(fell_filter)
    handler.setFormatter(fell_formatter)

    logging.basicConfig(handlers=[handler], force=True, level=logging.DEBUG)

    # Other Setup #############################################################
    DATA_DIR = Path(os.environ["FF_DATA_DIR"])

    # Landing #################################################################

    lidar_loader = LidarLoader()
    self = lidar_loader
    lidar_loader.run()
    del lidar_loader

    # Config set for execution on personal devices, not tuned for cloud
    builder = (
        SparkSession.builder.appName("fell_loader")
        .config("spark.master", "local[*]")
        .config("spark.driver.memory", "4g")
        .config("spark.driver.memoryOverhead", "1g")
        .config(
            "spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension"
        )
        .config(
            "spark.sql.catalog.spark_catalog",
            "org.apache.spark.sql.delta.catalog.DeltaCatalog",
        )
        .config("spark.log.level", "WARN")
        .config("spark.local.dir", (DATA_DIR / "temp" / "spark").as_posix())
    )

    spark = configure_spark_with_delta_pip(builder).getOrCreate()

    # TODO: Set this to skip load if osm file has not changed since last run

    osm_loader = OsmLoader(spark)
    osm_loader.run()
    del osm_loader

    # Staging #################################################################

    node_stager = NodeStager(spark)
    node_stager.run()
    del node_stager

    edge_stager = EdgeStager(spark)
    edge_stager.run()
    del edge_stager

    # Sanitising ##############################################################

    edge_sanitiser = EdgeSanitiser(spark)
    edge_sanitiser.run()
    del edge_sanitiser

    node_sanitiser = NodeSanitiser(spark)
    node_sanitiser.run()
    del node_sanitiser

    # Optimising ##############################################################

    graph_optimiser = GraphOptimiser(spark)
    graph_optimiser.run()
    del graph_optimiser

    spark.stop()

    # Load to Postgres ########################################################

    graph_uploader = GraphUploader()
    graph_uploader.run()
    del graph_uploader

    # Clear temp data #########################################################

    shutil.rmtree(
        path=(DATA_DIR / "temp").as_posix(),
    )
