"""Utility functions for the fell finder app. These are functions which
are helpful to the end user, but are not required for the app to run. Any
code which is a required element of the programme should be placed into the
relevant package.
"""

import logging
from datetime import datetime
from pathlib import Path


class FellFilter(logging.Filter):
    """Logging filter which returns only logs from fell_finder and its
    related packages
    """

    def filter(self, record: logging.LogRecord) -> bool:
        """Filter out records from upstream packages, retaining only those
        generated by fell_finder
        """
        return "fell_" in record.name or record.name == "__main__"


def set_up_logging() -> None:
    """Set up the logging module to write out internal logs to a folder"""
    # TODO: Add a retention period to logs
    log_dir = (Path.cwd()) / "logs"
    if not log_dir.exists():
        log_dir.mkdir()

    now = datetime.now().isoformat(timespec="seconds")
    handler = logging.FileHandler(filename=f"logs/{now}.log")

    fell_filter = FellFilter()

    # TODO: Update this to include line numbers
    fell_formatter = logging.Formatter(
        fmt="%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    )

    handler.addFilter(fell_filter)
    handler.setFormatter(fell_formatter)

    logging.basicConfig(handlers=[handler], force=True, level=logging.DEBUG)
