"""Functions relating to the loading of a .osm.pbf network graph into a tabular
format"""

import os
from glob import glob
import json

from functools import reduce
from copy import deepcopy
from pyspark.sql import DataFrame, functions as F, SparkSession

import daft
from bng_latlon import WGS84toOSGB36


import daft.functions
from fell_loader.utils.partitioning import add_partitions_to_daft_df

# TODO: Set this up to work with other filenames once moving to a fully
#       automated pipeline

# TODO: Plan out logic for using output from osm-parquetizer w. Daft. Need to
#       unpack the 'ways' output into edges. Expected schemas are:

# Nodes
# |-- id: long (nullable = true)
# |-- version: integer (nullable = true)
# |-- timestamp: long (nullable = true)
# |-- changeset: long (nullable = true)
# |-- uid: integer (nullable = true)
# |-- user_sid: string (nullable = true)
# |-- tags: array (nullable = true)
# |    |-- element: struct (containsNull = true)
# |    |    |-- key: string (nullable = true)
# |    |    |-- value: string (nullable = true)
# |-- latitude: double (nullable = true)
# |-- longitude: double (nullable = true)

# Ways
# |-- id: long (nullable = true)
# |-- version: integer (nullable = true)
# |-- timestamp: long (nullable = true)
# |-- changeset: long (nullable = true)
# |-- uid: integer (nullable = true)
# |-- user_sid: string (nullable = true)
# |-- tags: array (nullable = true)
# |    |-- element: struct (containsNull = true)
# |    |    |-- key: string (nullable = true)
# |    |    |-- value: string (nullable = true)
# |-- nodes: array (nullable = true)
# |    |-- element: struct (containsNull = true)
# |    |    |-- index: integer (nullable = true)
# |    |    |-- nodeId: long (nullable = true)


# Nodes
# - Select id, latitude and longitude
# - Check in tags for anything useful

# Edges
# - Start with Ways
# - Explode out to one record per way ID, per node, retaining index in way
# - Get dst with offset
# - Extract oneway flag from tags
# - Generate reverse edges where appropriate
# - Join on nodes to get lat/lon


class OsmLoader:
    """Reads in the contents of the provided OSM extract. Generates two parquet
    datasets containing details of the graph nodes and edges. These datasets
    are partitioned according to the british national grid system to improve
    access speed in downstream applications."""

    def __init__(self, spark: SparkSession) -> None:
        """Create an instance of the OSM loader, store down the directory which
        contains the data to be loaded."""

        self.spark = spark
        self.data_dir = os.environ["FF_DATA_DIR"]
        self.binary_loc = os.environ["FF_PARQUETIZER_LOC"]

        self.nodes_loc = ""
        self.ways_loc = ""
        self.relations_loc = ""

    def _set_parquet_locs(self) -> None:
        """Store the location of the parquet files generated by osm-parquetizer
        as a class attribute for convenience.

        Raises:
            FileNotFoundError: If no .parquet files are detected, an exception
                will be raised.

        """
        osm_loc = os.path.join(self.data_dir, "extracts", "osm")

        nodes_loc = glob(os.path.join(osm_loc, "*.node.parquet"))
        ways_loc = glob(os.path.join(osm_loc, "*.way.parquet"))
        relations_loc = glob(os.path.join(osm_loc, "*.relation.parquet"))

        try:
            self.nodes_loc = nodes_loc[0]
            self.ways_loc = ways_loc[0]
            self.relations_loc = relations_loc[0]
        except IndexError:
            raise FileNotFoundError(
                f"Unable to find generated parquet files in {osm_loc}. Please "
                "ensure you have called unpack_osm_pbf, and check the job"
                "logs"
            )

    def unpack_osm_pbf(self) -> None:
        """Use the osm-parquetizer utility to unpack the provided osm.pbf file
        in the extracts/osm directory into parquet files. These can then be
        read in as dataframes for further processing.

        Raises:
            FileNotFoundError: If no osm.pbf file is found in the extracts/osm
                subfolder of the data directory, an exception will be raised
            RuntimeError: If multile osm.pbf files are found in the
                extracts/osm subfolder of the data directory, an exception will
                be raised

        """

        pbf_loc = glob(
            os.path.join(self.data_dir, "extracts", "osm", "*.osm.pbf")
        )

        if not pbf_loc:
            raise FileNotFoundError(f"No osm.pbf file detected in {pbf_loc}")
        elif len(pbf_loc) > 1:
            pbf_str = ", ".join(pbf_loc)
            raise RuntimeError(
                f"Multiple osm.pbf files detected in {pbf_loc}: {pbf_str}"
            )
        else:
            pbf_loc = pbf_loc[0]

        os.system(f"java -jar {self.binary_loc} {pbf_loc}")

        self._set_parquet_locs()

    def read_unpacked_data(self) -> tuple[DataFrame, DataFrame]:
        nodes_df = self.spark.read.parquet(self.nodes_loc)
        ways_df = self.spark.read.parquet(self.ways_loc)

        return nodes_df, ways_df

    @staticmethod
    def assign_bng_coords(nodes: daft.DataFrame) -> daft.DataFrame:
        """Assign each node an easting and northing, this will be used to
        split the nodes dataset into partitions according to their geographical
        location

        Args:
            nodes: The nodes dataframe

        Returns:
            A copy of the input dataframe with additional easting and northing
            columns

        """

        @daft.udf(return_dtype=daft.DataType.list(daft.DataType.float64()))
        def bng_udf(lats: daft.Series, lons: daft.Series) -> daft.Series:
            bng_coords = [
                WGS84toOSGB36(lat, lon) for lat, lon in zip(lats, lons)
            ]
            return bng_coords  # type: ignore

        nodes = nodes.with_column(
            "bng_coords", bng_udf(daft.col("latitude"), daft.col("longitude"))
        )

        nodes = nodes.with_column(
            "easting",
            daft.col("bng_coords").list.get(0).cast(daft.DataType.int32()),
        )

        nodes = nodes.with_column(
            "northing",
            daft.col("bng_coords").list.get(1).cast(daft.DataType.int32()),
        )

        nodes = nodes.exclude("bng_coords")

        return nodes

    # Nodes
    # |-- id: long (nullable = true)
    # |-- version: integer (nullable = true)
    # |-- timestamp: long (nullable = true)
    # |-- changeset: long (nullable = true)
    # |-- uid: integer (nullable = true)
    # |-- user_sid: string (nullable = true)
    # |-- tags: array (nullable = true)
    # |    |-- element: struct (containsNull = true)
    # |    |    |-- key: string (nullable = true)
    # |    |    |-- value: string (nullable = true)
    # |-- latitude: double (nullable = true)
    # |-- longitude: double (nullable = true)

    @staticmethod
    def set_node_output_schema(nodes: daft.DataFrame) -> daft.DataFrame:
        """Ensure the node output dataset contains only the required columns

        Args:
            nodes: A polars dataframe containing details of all nodes in the
              graph

        Returns:
            A subset of the provided dataframe

        """
        nodes = nodes.select(
            "id",
            daft.col("latitude").alias("lat"),
            daft.col("longitude").alias("lon"),
            "easting",
            "northing",
            "easting_ptn",
            "northing_ptn",
        )
        return nodes

    # Ways
    # |-- id: long (nullable = true)
    # |-- version: integer (nullable = true)
    # |-- timestamp: long (nullable = true)
    # |-- changeset: long (nullable = true)
    # |-- uid: integer (nullable = true)
    # |-- user_sid: string (nullable = true)
    # |-- tags: array (nullable = true)
    # |    |-- element: struct (containsNull = true)
    # |    |    |-- key: string (nullable = true)
    # |    |    |-- value: string (nullable = true)
    # |-- nodes: array (nullable = true)
    # |    |-- element: struct (containsNull = true)
    # |    |    |-- index: integer (nullable = true)
    # |    |    |-- nodeId: long (nullable = true)

    @staticmethod
    def unpack_tags(ways: daft.DataFrame) -> daft.DataFrame:
        """Transform the tags for each way from the input format:

            [{tag_1: value_1}, {tag_2: value_2}]

        into a more usable JSON struct:

            {tag_1: value_1, tag_2: value_2}

        Note that JSON must be used, as UDFs cannot currently return mappings.
        At present, there does not seem to be any built-in function which can
        achieve the desired effect.

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A view of the input dataframe, with a processed tags column

        """

        # TODO: Confirm that utf8 is the correct encoding

        @daft.udf(return_dtype=daft.DataType.string())
        def tags_udf(tags_list: daft.Series) -> daft.Series:
            output = []

            for tags in tags_list:
                if not tags:
                    output.append("{}")
                else:
                    tags_dict = {}
                    for tag in tags:
                        key = tag["key"].decode("utf8")
                        value = tag["value"].decode("utf8")
                        tags_dict[key] = value
                    output.append(json.dumps(tags_dict))

            return output  # type: ignore

        ways = ways.with_column("tags", tags_udf(daft.col("tags")))

        return ways

    @staticmethod
    def _get_tag_as_column(
        df: daft.DataFrame, tag_name: str
    ) -> daft.DataFrame:
        df = df.with_column(
            tag_name,
            daft.col("tags").json.query(f".{tag_name}").str.replace('"', ""),
        )

        return df

    def remove_restricted_routes(self, ways: daft.DataFrame) -> daft.DataFrame:
        """Remove any ways which correspond to routes with access controls,
        which are not usable by the public

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A filtered copy of the input dataset

        """

        ways = self._get_tag_as_column(ways, "access")

        accessible_mask = daft.col("access").is_in(
            ["yes", "permissive", "designated", "null"]
        )

        ways = ways.filter(accessible_mask).exclude("access")

        return ways

    def set_flat_flag(self, ways: daft.DataFrame) -> daft.DataFrame:
        """For any edges which correspond to a feature which means data from
        a terrain model for elevation will not apply (i.e. a bridge or a
        tunnel), set a flag to ensure the elevation data for these edges is
        masked.

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A copy of the input dataset with an additional boolean
            'is_flat' column

        """

        ways = self._get_tag_as_column(ways, "bridge")
        ways = self._get_tag_as_column(ways, "tunnel")

        ways = ways.with_column(
            "is_flat",
            (daft.col("bridge") != daft.lit("null"))
            | (daft.col("tunnel") != daft.lit("null")),
        ).exclude("bridge", "tunnel")

        return ways

    def set_oneway_flag(self, ways: daft.DataFrame) -> daft.DataFrame:
        """For any routes which are not one-way, we will need to create a
        reversed view to enable graph traversal in both directions. This
        information is recorded in the tags, so we must retrieve it for
        ease of use.

        Args:
            ways: A dataframe containing the ways from the OSM extract

        Returns:
            A copy of the input dataset with an additional boolean 'oneway'
            column

        """

        ways = self._get_tag_as_column(ways, "oneway")

        ways = ways.with_column(
            "oneway",
            ~daft.col("oneway").is_in(["no", "null"]),
        )

        return ways

    # Ways
    # |-- id: long (nullable = true)
    # |-- version: integer (nullable = true)
    # |-- timestamp: long (nullable = true)
    # |-- changeset: long (nullable = true)
    # |-- uid: integer (nullable = true)
    # |-- user_sid: string (nullable = true)
    # |-- tags: array (nullable = true)
    # |    |-- element: struct (containsNull = true)
    # |    |    |-- key: string (nullable = true)
    # |    |    |-- value: string (nullable = true)
    # |-- nodes: array (nullable = true)
    # |    |-- element: struct (containsNull = true)
    # |    |    |-- index: integer (nullable = true)
    # |    |    |-- nodeId: long (nullable = true)

    @staticmethod
    def generate_edges(ways: daft.DataFrame) -> daft.DataFrame:
        # Bring through index as way_inx, as well as src node
        # Window fn to pull through dst
        # Drop any records with null dst
        edges = ways.explode(daft.col("nodes"))

        edges = edges.with_columns(
            {
                "way_inx": daft.col("nodes").struct.get("index"),
                "src": daft.col("nodes").struct.get("nodeId"),
            }
        )

        window_spec = (
            daft.Window()
            .partition_by(daft.col("id"))
            .order_by(daft.col("way_inx"))
        )

        edges = edges.with_column(
            "dst", daft.col("src").lead().over(window_spec)
        )

        edges = edges.drop_null(daft.col("src"), daft.col("dst"))

        edges = edges.exclude("nodes").with_column_renamed("id", "way_id")

        return edges

    @staticmethod
    def add_reverse_edges(edges: daft.DataFrame) -> daft.DataFrame:
        """For any edges A-B where the oneway field is either NULL or
        explicitlyset to no, create a second edge B-A. Assign this new edge
        to a new way, and record its position in the dataframe. The geometry
        of a way is set by the position of each edge in the dataframe, so it
        is important that this information be retained.

        Args:
            edges: A dataframe containing details of all edges in the graph

        Returns:
            A copy of the input dataframe, with any bi-directional edges
            explicitly represented in both directions

        """
        reverse = edges.filter(~daft.col("oneway"))

        reverse = reverse.with_columns(
            {"old_src": daft.col("src"), "src": daft.col("dst")}
        )

        reverse = reverse.with_columns(
            {
                "dst": daft.col("old_src"),
                "way_id": daft.col("way_id") * daft.lit(-1),
                "way_inx": daft.col("way_inx") * daft.lit(-1),
            }
        )

        reverse = reverse.exclude("old_src")

        out = edges.concat(reverse)

        return out

    @staticmethod
    def get_edge_start_coords(
        nodes: daft.DataFrame, edges: daft.DataFrame
    ) -> daft.DataFrame:
        """For each edge in the graph, work out its starting position by
        joining on details of the source node.

        Args:
            nodes: A polars dataframe containing details of all nodes in the
              graph
            edges: A polars dataframe containing details of all edges in the
              graph

        Returns:
            A copy of the edges dataframe with additional src_lat, src_lon,
            src_easting, src_northing, easting_ptn and northing_ptn columns

        """
        nodes = nodes.select(
            daft.col("id").alias("src"),
            daft.col("lat").alias("src_lat"),
            daft.col("lon").alias("src_lon"),
            daft.col("easting").alias("src_easting"),
            daft.col("northing").alias("src_northing"),
            "easting_ptn",
            "northing_ptn",
        )

        edges = edges.join(nodes, on="src", how="inner")

        return edges

    @staticmethod
    def get_edge_end_coords(
        nodes: daft.DataFrame, edges: daft.DataFrame
    ) -> daft.DataFrame:
        """For each edge in the graph, work out its final position by joining
        on details of the destination node.

        Args:
            nodes: A polars dataframe containing details of all nodes in the
              graph
            edges: A polars dataframe containing details of all edges in the
              graph

        Returns:
            A copy of the edges dataframe with additional dst_lat, dst_lon,
            dst_easting and dst_northing columns

        """
        nodes = nodes.select(
            daft.col("id").alias("dst"),
            daft.col("lat").alias("dst_lat"),
            daft.col("lon").alias("dst_lon"),
            daft.col("easting").alias("dst_easting"),
            daft.col("northing").alias("dst_northing"),
        )

        edges = edges.join(nodes, on="dst", how="inner")

        return edges

    # Ways
    # |-- id: long (nullable = true)
    # |-- version: integer (nullable = true)
    # |-- timestamp: long (nullable = true)
    # |-- changeset: long (nullable = true)
    # |-- uid: integer (nullable = true)
    # |-- user_sid: string (nullable = true)
    # |-- tags: array (nullable = true)
    # |    |-- element: struct (containsNull = true)
    # |    |    |-- key: string (nullable = true)
    # |    |    |-- value: string (nullable = true)
    # |-- nodes: array (nullable = true)
    # |    |-- element: struct (containsNull = true)
    # |    |    |-- index: integer (nullable = true)
    # |    |    |-- nodeId: long (nullable = true)

    @staticmethod
    def set_edge_output_schema(edges: daft.DataFrame) -> daft.DataFrame:
        """Ensure the edge output dataset contains only the required columns

        Args:
            edges: A polars dataframe containing details of all edges in the
              graph

        Returns:
            A subset of the provided dataframe

        """

        edges = edges.select(
            "src",
            "dst",
            daft.col("id").alias("way_id"),
            "way_inx",
            daft.col("tags").map.get(daft.lit("highway")).alias("highway"),
            daft.col("tags").map.get(daft.lit("surface")).alias("surface"),
            "is_flat",
            "src_lat",
            "src_lon",
            "dst_lat",
            "dst_lon",
            "src_easting",
            "src_northing",
            "dst_easting",
            "dst_northing",
            "easting_ptn",
            "northing_ptn",
        )
        return edges

    def write_nodes_to_parquet(self, nodes: daft.DataFrame) -> None:
        """Write the provided dataframe out to parquet format, partitioning
        by easting_ptn and northing_ptn

        Args:
            nodes: The dataframe to be written

        """

        tgt_loc = os.path.join(self.data_dir, "parsed/nodes")

        nodes.write_parquet(
            tgt_loc, partition_cols=["easting_ptn", "northing_ptn"]
        )

    def write_edges_to_parquet(self, edges: daft.DataFrame) -> None:
        """Write the provided dataframe out to parquet format, partitioning
        by easting_ptn and northing_ptn

        Args:
            edges: The dataframe to be written

        """
        tgt_loc = os.path.join(self.data_dir, "parsed/edges")

        edges.write_parquet(
            tgt_loc,
            partition_cols=["easting_ptn", "northing_ptn"],
        )

    def load(self) -> None:
        """End-to-end data load script for an OSM extract. This will read in
        the contents of the file using pyrosm, perform some basic processing to
        ensure the resultant graph will be bidirectional and way geometry
        will be preserved when processed by pyspark. Nodes and edges will be
        assigned to partitions according to eastings & northings before being
        written out to disk.
        """

        self.unpack_osm_pbf()

        nodes, ways = self.read_unpacked_data()

        nodes = self.assign_bng_coords(nodes)
        nodes = add_partitions_to_daft_df(nodes)
        nodes = self.set_node_output_schema(nodes)

        ways = self.unpack_tags(ways)
        ways = self.remove_restricted_routes(ways)
        ways = self.set_flat_flag(ways)
        ways = self.set_oneway_flag(ways)

        edges = self.generate_edges(ways)
        edges = self.add_reverse_edges(ways)
        edges = self.get_edge_start_coords(nodes, edges)
        edges = self.get_edge_end_coords(nodes, edges)
        edges = self.set_edge_output_schema(edges)

        self.write_nodes_to_parquet(nodes)
        self.write_edges_to_parquet(edges)
