"""Defines a function which can be used to initialize the callbacks used in
the route finder page
"""

import json
import os
import time
from collections.abc import Callable
from typing import Any, Literal

import dash_bootstrap_components as dbc
import dash_leaflet as dl
from dash import ALL, Input, Output, Patch, State, callback, ctx, no_update
from dash._callback import NoUpdate  # type: ignore
from plotly.graph_objects import Figure

from fell_viewer.common.app import background_callback_manager
from fell_viewer.common.containers import RouteConfig
from fell_viewer.content.route_finder.components.cards import RouteCard
from fell_viewer.content.route_finder.generators import (
    generate_elevation_plot,
)
from fell_viewer.utils.api import (
    get_job_results,
    get_job_status,
    request_new_route,
)
from fell_viewer.utils.caching import (
    load_routes_from_str,
    store_routes_to_str,
)
from fell_viewer.utils.encoding import get_image_as_str

CUR_DIR = os.path.dirname(os.path.abspath(__file__))

MAP_PIN_PNG = get_image_as_str("map_pin.png")
ROUTE_START_PNG = get_image_as_str("route_start.png")

MAX_JOB_DURATION = int(os.environ.get("FF_MAX_JOB_SECONDS", "600"))

with open(
    os.path.join(CUR_DIR, "highway_types.json"), encoding="utf8"
) as file:
    HIGHWAY_TYPES = json.load(file)

with open(
    os.path.join(CUR_DIR, "surface_types.json"), encoding="utf8"
) as file:
    SURFACE_TYPES = json.load(file)


def init_callbacks() -> None:  # noqa: PLR0915
    """This function needs to be called in a function which defines elements of
    the page config in order to ensure the enclosed callbacks are correctly
    registered
    """
    # ruff: noqa: ANN202

    @callback(
        Output("route-plot", "children", allow_duplicate=True),
        Input("route-plot", "clickData"),
        State("route-plot", "children"),
        prevent_initial_call=True,
    )
    def show_clicked_point_on_map(click_data: dict, current_children: list):
        """Whenever the user clicks a point on the route, add a marker to the
        map at the selected point

        Args:
            click_data: The data generated by Dash to signify a user click
            current_children: The current contents of the primary plot

        Returns:
            The updated contents of the route plot, with the old marker removed
            and a new one added

        """
        if click_data is None:
            return no_update

        lat = click_data["latlng"]["lat"]
        lon = click_data["latlng"]["lng"]

        new_marker = dl.Marker(
            position=[lat, lon],  # type: ignore
            id="route-plot-marker",
            icon={
                "iconUrl": ROUTE_START_PNG,
                "iconSize": [48, 48],
                "iconAnchor": [24, 48],
            },
        )

        new_children = [
            child
            for child in current_children
            if child["props"]["id"] != "route-plot-marker"
        ]
        new_children.append(new_marker)

        return new_children

    @callback(
        Output("route-restricted-surfaces", "options"),
        Input("route-allowed-surfaces", "value"),
    )
    def update_restriction_options(route_allowed_surfaces: list[str]):
        return route_allowed_surfaces

    # Required Callbacks (new setup)
    # Request route (success/fail)
    #  - Send request, store job ID internally
    # Poll for updates
    #  - Trigger when internal job ID is updated
    #  - Update progress bar once per second
    # Retrieve routes
    #  -

    @callback(
        [Output("route-current-job", "data")],
        Input("route-calculate-button", "n_clicks"),
        [
            State("route-plot", "children"),
            State("route-dist", "value"),
            State("route-mode", "value"),
            State("route-highway", "value"),
            State("route-allowed-surfaces", "value"),
            State("route-restricted-surfaces", "value"),
            State("route-restricted-perc", "value"),
        ],
        prevent_initial_call=True,
    )
    def request_new_route_from_input(  # noqa: PLR0913
        n_clicks: int | None,
        current_children: list,
        route_dist: str,
        route_mode: Literal["hilly", "flat"],
        route_highways: list[str],
        route_allowed_surfaces: list[str],
        route_restricted_surfaces: list[str],
        route_restricted_perc: int,
    ):
        """Trigger the creation of a new route. This will spawn a background
        job in the fell_finder backend and return a job ID. This job ID can
        be used to poll for updates on the current job, and retrieve the
        results once completed

        Args:
            n_clicks: The number of times the calculate button has been clicked
            current_children: The contents of the current route plot
            route_dist: The user requested distance
            route_mode: The user requested mode (hilly/flat)
            route_highways: The user requested highways
            route_allowed_surfaces: The user requested surfaces
            route_restricted_surfaces: Surfaces which are to be restricted to
              a percentage of the total distance
            route_restricted_perc: The max allowed percentage of the total
              distance which can be travelled on the restricted surfaces

        Returns:
            An ID for for the route creation job which has been spawned

        """
        if not n_clicks:
            return no_update

        current_marker = next(
            x
            for x in current_children
            if x["props"]["id"] == "route-plot-marker"
        )
        lat, lon = current_marker["props"]["position"]

        highway_types = []
        for highway_type in route_highways:
            highway_types += HIGHWAY_TYPES[highway_type]

        surface_types = []
        for surface_type in route_allowed_surfaces:
            surface_types += SURFACE_TYPES[surface_type]

        restricted_surfaces = []
        for surface_type in route_restricted_surfaces:
            restricted_surfaces += SURFACE_TYPES[surface_type]

        config = RouteConfig(
            start_lat=lat,
            start_lon=lon,
            target_distance=int(route_dist) * 1000,
            route_mode=route_mode,
            highway_types=highway_types,
            surface_types=surface_types,
            restricted_surfaces=restricted_surfaces,
            restricted_surfaces_perc=route_restricted_perc / 100.0,
        )

        job_id = request_new_route(config)

        return [job_id]

    def _generate_bar_for_status(
        status: dict[str, str],
    ) -> dbc.Progress:
        match status["status"]:
            case ("queued", "started"):
                value = 0
                colour = "secondary"
            case "error":
                value = 1
                colour = "danger"
            case "success":
                value = 1
                colour = "success"
            case _:  # This should never happen
                value = 1
                colour = "secondary"

        new_bar = dbc.Progress(
            id="route-progress",
            min=0,
            max=1,
            value=value,
            color=colour,
            striped=True,
            animated=False,
        )
        return new_bar

    def _generate_bar_for_calculation(
        detail: dict[str, int | float],
    ) -> dbc.Progress | Patch:
        # TODO: Get this working with partial updates to reduce traffic

        match detail["attempt"]:
            case 1:
                colour = "blue"
            case 2:
                colour = "indigo"
            case _:
                colour = "purple"

        return dbc.Progress(
            id="route-progress",
            min=0,
            max=detail["target"],
            value=detail["current"],
            color=colour,
            striped=True,
            animated=True,
        )

    def _check_if_update_required(
        status: dict, last_status: dict
    ) -> Literal["full", "partial", "none"]:
        cur_stat = status["status"]
        cur_dtl = status["detail"]
        last_stat = status["status"]
        last_dtl = last_status["detail"]

        if cur_stat != last_stat:
            return "full"

        if cur_dtl == last_dtl:
            return "none"

        if isinstance(cur_dtl, dict) and isinstance(last_dtl, dict):
            # Detail only populated during calculation, so this will only occur
            # midway through a calculation
            return "partial"

        return "full"

    @callback(
        [Output("route-last-job-status", "data")],
        Input("route-current-job", "data"),
        progress=Output("route-progress-container", "children"),
        background=True,
        prevent_initial_call=True,
        manager=background_callback_manager,
    )
    def poll_until_job_completion(update_progress: Callable, job_id: str):
        """Continuously poll the fell_finder API for the status of the latest
        job. Periodically update the progress bar to keep the user informed
        as routes are generated.

        Args:
            update_progress: A handle which can be used to update the progress
                bar
            job_id: The ID for the current job

        Raises:
            ValueError: If the API returns an unrecognised response, an
                exception will be raised

        Returns:
            A json encoded dict, which contains 'status', 'detail' and 'job_id'
            keys

        """
        status: dict[str, Any] = {"status": "queued", "detail": None}
        last_status: dict[str, Any] = {"status": None, "detail": None}

        update_progress(_generate_bar_for_status(status))

        while status["status"] not in ("success", "error"):
            last_status = status
            status = get_job_status(job_id)

            code = status["status"]
            dtl = status["detail"]

            if code in {"started", "error", "success", "queued"}:
                time.sleep(1)

            elif code == "calculating":
                match _check_if_update_required(status, last_status):
                    case "none":
                        pass
                    case "full":
                        update_progress(_generate_bar_for_calculation(dtl))
                    case "partial":
                        update_progress(_generate_bar_for_calculation(dtl))

                time.sleep(1)

            else:
                raise ValueError("Unhandled job status")

        update_progress(_generate_bar_for_status(status))

        status["job_id"] = job_id

        return [json.dumps(status)]

    @callback(
        [
            Output("route-store", "data"),
            Output("route-error-toast", "children"),
            Output("route-error-toast", "is_open"),
        ],
        Input("route-last-job-status", "data"),
        prevent_initial_call=True,
    )
    def retrieve_and_store_routes(status_str: str):
        """Once a job has completed, check the status. If an error was
        encountered, display a popup to the user showing details of what went
        wrong. If routes were generated successfully, store them in memory
        ready to be displayed by downstream callbacks.

        Args:
            status_str: A json-encoded dict containing the result of the last
                job

        Returns:
            A json-encoded string containing details of any generated routes

        """
        status = json.loads(status_str)

        if status["status"] == "error":
            error_dtl = status["detail"]
            return ([], error_dtl, True)

        # TODO: Handle error status, set up toast popups

        # TODO: Make sure API returns an error type if no routes were generated
        #       after the last attempt

        routes = get_job_results(status["job_id"])

        routes_str = store_routes_to_str(routes)

        return (routes_str, "success", False)

    @callback(
        [
            Output("route-tabs", "active_tab"),
            Output("route-cards", "children"),
        ],
        Input("route-store", "data"),
        prevent_initial_call=True,
    )
    def select_view_tab_and_render_cards(
        cached_routes: str,
    ) -> tuple[NoUpdate, NoUpdate] | tuple[str, list[dbc.Card]]:
        if not cached_routes:
            return no_update, no_update

        new_routes = load_routes_from_str(cached_routes)

        cards = [RouteCard(route).generate() for route in new_routes]

        return "route-tab-cards", cards

    @callback(
        [
            Output("route-plot", "children", allow_duplicate=True),
            Output("route-plot", "viewport", allow_duplicate=True),
            Output("route-profile", "figure", allow_duplicate=True),
        ],
        Input("route-store", "data"),
        State("route-plot", "children"),
        prevent_initial_call=True,
    )
    def update_primary_plot_on_calculation(
        cached_routes: str, current_children: list
    ) -> tuple[NoUpdate, NoUpdate, NoUpdate] | tuple[list, dict, Figure]:
        """When the user selects a new route for display in the primary plot,
        fetch the relevant data and render it as a polyline

        Args:
            search_str: The requested route ID
            cached_routes: The cached route data
            current_children: The current contents of the primary plot
            current_page: The currently selected page

        Returns:
            The updated contents of the primary plot, with any old polylines
            removed and a new one added

        """
        if not cached_routes:
            return no_update, no_update, no_update

        new_routes = load_routes_from_str(cached_routes)

        route = new_routes[0]

        polyline = route.to_polyline(element_id="route-plot-trace")

        viewport = route.geometry.bbox.to_viewport()

        new_children = [
            x
            for x in current_children
            if x["props"]["id"] != "route-plot-trace"
        ]
        new_children.append(polyline)

        profile_plot = generate_elevation_plot(route)

        return new_children, viewport, profile_plot

    @callback(
        [
            Output("route-plot", "children", allow_duplicate=True),
            Output("route-plot", "viewport", allow_duplicate=True),
            Output("route-profile", "figure", allow_duplicate=True),
        ],
        Input({"type": "route-view-button", "route-id": ALL}, "n_clicks"),
        [
            State({"type": "route-view-button", "route-id": ALL}, "id"),
            State("route-store", "data"),
            State("route-plot", "children"),
        ],
        prevent_initial_call=True,
    )
    def update_primary_plot_on_view_click(
        all_n_clicks: list[int],
        all_ids: list[dict],
        cached_routes: str,
        current_children: list,
    ) -> tuple[NoUpdate, NoUpdate, NoUpdate] | tuple[list, dict, Figure]:
        """When the user selects a new route for display in the primary plot,
        fetch the relevant data and render it as a polyline

        Args:
            all_n_clicks: The number of clicks for all of the 'View' buttons
                on route cards
            all_ids: The IDs for all of the 'View' buttons on route
                cards
            cached_routes: The contents of the route cache, a JSON encoded
                string containing the details of all generated routes
            current_children: The current contents of the primary plot

        Returns:
            The updated contents of the primary plot, with any old polylines
            removed and a new one added

        """
        # Determine which route was clicked
        if not ctx.triggered_id:
            raise ValueError("Something went wrong updating the plot")
        target_id = ctx.triggered_id["route-id"]

        # Get the number of clicks for the selected route
        n_clicks = 0
        for maybe_n_clicks, maybe_route_id in zip(all_n_clicks, all_ids):
            if maybe_route_id["route-id"] == target_id:
                n_clicks = maybe_n_clicks
                break

        if (not n_clicks) or (not cached_routes):
            return no_update, no_update, no_update

        routes = load_routes_from_str(cached_routes)

        # Fetch the selected route
        route = next(x for x in routes if str(x.route_id) == target_id)

        polyline = route.to_polyline(element_id="route-plot-trace")

        viewport = route.geometry.bbox.to_viewport()

        # Clear out the old polyline & markers, retain the tile layer
        new_children = [
            x
            for x in current_children
            if x["props"]["id"] not in {"route-plot-trace", "selected-point"}
        ]
        new_children.append(polyline)

        profile_plot = generate_elevation_plot(route)

        return new_children, viewport, profile_plot

    @callback(
        Output("route-download", "data"),
        Input({"type": "route-dl-button", "route-id": ALL}, "n_clicks"),
        [
            State({"type": "route-dl-button", "route-id": ALL}, "id"),
            State("route-store", "data"),
        ],
        prevent_initial_call=True,
    )
    def download_gpx_on_dl_click(
        all_n_clicks: list[int], all_ids: list[dict], cached_routes: str
    ) -> NoUpdate | dict[str, str]:
        """When the user selects a new route for display in the primary plot,
        fetch the relevant data and render it as a polyline

        Args:
            all_n_clicks: The number of clicks for all of the 'View' buttons
                on route cards
            all_ids: The IDs for all of the 'View' buttons on route
                cards
            cached_routes: The contents of the route cache, a JSON encoded
                string containing the details of all generated routes

        Returns:
            The details of a GPX file to trigger a download for

        """
        # Determine which route was clicked
        if not ctx.triggered_id:
            raise ValueError("Something went wrong updating the plot")
        target_id = ctx.triggered_id["route-id"]

        # Get the number of clicks for the selected route
        n_clicks = 0
        for maybe_n_clicks, maybe_route_id in zip(all_n_clicks, all_ids):
            if maybe_route_id["route-id"] == target_id:
                n_clicks = maybe_n_clicks
                break

        if (not n_clicks) or (not cached_routes):
            return no_update

        routes = load_routes_from_str(cached_routes)

        # Fetch the selected route
        route = next(x for x in routes if str(x.route_id) == target_id)

        gpx_data = route.geometry.to_gpx()

        dl_data = {
            "filename": f"found-fell-{target_id}.gpx",
            "content": gpx_data,
        }

        return dl_data

    @callback(
        Output("route-plot", "children", allow_duplicate=True),
        Input("route-profile", "hoverData"),
        State("route-plot", "children"),
        prevent_initial_call=True,
    )
    def update_map_based_on_profile(
        hover_data: dict | None, current_children: list
    ):
        """When the user hovers over the elevation profile, place a marker on
        the map at the corresponding location.

        Args:
            hover_data: Data on the currently selected point on the profile
            current_children: The current contents of the route plot

        Returns:
            The different layers required to plot the route and the selected
            point on the map

        """
        if hover_data is None:
            return no_update

        lat_lon = hover_data["points"][0]["customdata"]

        route_marker = dl.Marker(
            position=lat_lon,
            id="selected-point",
            icon={
                "iconUrl": MAP_PIN_PNG,
                "iconSize": [48, 48],
                "iconAnchor": [24, 48],
            },
        )

        new_children = [
            x for x in current_children if x["props"]["id"] != "selected-point"
        ]

        new_children.append(route_marker)

        return new_children
